variables:
  GLOBAL_BASE_IMAGE: pubrepo.jiagouyun.com/base/golang:1.25.8
  DEP_IMAGE: registry.jiagouyun.com/basis/kodo-dep-go1.25.8
  CACHE_IMAGE_PATH: image-cache
  PROJECT: "graphdb"
  CONTAINER_NAME: "graphdb"
  WORKDIR_IMAGE: /work/src/graphdb

stages:
  - build-dep
  - build
  - deploy

build-dep:
  stage: build-dep
  when: manual
  variables:
    BASE_IMAGE: $GLOBAL_BASE_IMAGE
  script:
    - echo $DEP_IMAGE
    - echo $BASE_IMAGE
    - docker rmi -f $DEP_IMAGE:latest || true
    - docker build --build-arg BASE_IMAGE=$BASE_IMAGE --build-arg GOPRIVATE=gitlab.jiagouyun.com --build-arg GIT_USER=$gitadmin_token_user --build-arg GIT_TOKEN=$gitadmin_token_pass -t $DEP_IMAGE:latest -f ./image/Dockerfile.dep .  
    - docker push $DEP_IMAGE:latest
  tags:
    - cloudcare-multiarch

build-testing:
  stage: build
  resource_group: production
  only:
    - /^testing-.*$/ # any `testing-xxx' feature branches allowed to fire testing release
  script:
    - docker rm -f $CONTAINER_NAME || true
    - start_time=`date +%s`
    - docker run --name $CONTAINER_NAME --rm -v $(pwd):$WORKDIR_IMAGE -w $WORKDIR_IMAGE $DEP_IMAGE make build-$(go env GOARCH)
    - compile_time=`date +%s`; echo compile `expr $compile_time - $start_time` s.
    - docker build --build-arg DEP_IMAGE=$DEP_IMAGE -t registry.jiagouyun.com/kodo/kodo:$CI_COMMIT_REF_NAME -t pubrepo.jiagouyun.com/cloudcare-forethought/kodo:$CI_COMMIT_REF_NAME -f ./image/Dockerfile .
    - image_time=`date +%s`; echo build image `expr $image_time - $compile_time` s.
    - docker push registry.jiagouyun.com/kodo/kodo:$CI_COMMIT_REF_NAME
    - push_time=`date +%s`; echo push image `expr $push_time - $image_time` s.
  after_script:
    - docker rm -f $CONTAINER_NAME || true
  tags:
    - cloudcare-multiarch


build-release:
  stage: build
  resource_group: production
  only:
    - /^release(\/|-)?.*$/ # any `testing-xxx' feature branches allowed to fire testing release
  script:
    - docker run --rm -v $(pwd):$WORKDIR_IMAGE -w $WORKDIR_IMAGE $DEP_IMAGE make build
    - docker buildx build --build-arg DEP_IMAGE=$DEP_IMAGE --platform linux/arm64,linux/amd64 -t registry.jiagouyun.com/kodo/kodo:$CI_COMMIT_REF_NAME -t pubrepo.jiagouyun.com/cloudcare-forethought/kodo:$CI_COMMIT_REF_NAME -f ./image/Dockerfile . --push #--cache-from=$CACHE_IMAGE_PATH
  tags:
    - cloudcare-multiarch

build-preprod:
  stage: build
  resource_group: production
  only:
    - /^pre(\/|-)?.*$/
  script:
    - docker run --rm -v $(pwd):$WORKDIR_IMAGE -w $WORKDIR_IMAGE $DEP_IMAGE make build
    - make pub_registry_image VERSION=$CI_COMMIT_REF_NAME
  tags:
    - cloudcare-multiarch

deployProd:
  stage: deploy
  resource_group: production
  only:
    - /^deploy_\d+/
  script:
    - sh cd.sh -d
  tags:
    - cloudcare-multiarch

buildRTM:
  stage: build
  resource_group: production
  only:
    - /\d+\.\d+\.\d+-\w+-\d+-prod/
  script:
    - V=(${CI_COMMIT_REF_NAME//[\.-]/ })
    - VDIR=${V[0]}.${V[1]}.${V[2]}
    - REPO=dataflux/$VDIR
    - TAG=${PROJECT}-${V[3]}-${V[4]}
    - docker run --rm -v $(pwd):$WORKDIR_IMAGE -w $WORKDIR_IMAGE $DEP_IMAGE make build
    - make pub_pubrepo_image REPO=$REPO:$TAG DEP_IMAGE=$DEP_IMAGE
  tags:
    - cloudcare-multiarch

buildUOSRTM:
  stage: build
  resource_group: production
  only:
    - /\d+\.\d+\.\d+-\w+-\d+-uos-prod/
  script:
    - V=(${CI_COMMIT_REF_NAME//[\.-]/ })
    - VDIR=${V[0]}.${V[1]}.${V[2]}
    - REPO=uos-dataflux/$VDIR
    - TAG=${PROJECT}-${V[3]}-${V[4]}
    - docker run --rm -v $(pwd):$WORKDIR_IMAGE -w $WORKDIR_IMAGE $DEP_IMAGE make build
    - make pub_pubrepo_uos_image REPO=$REPO:$TAG DEP_IMAGE=$DEP_IMAGE
  tags:
    - cloudcare-multiarch

buildRTMPrev:
  stage: build
  resource_group: production
  only:
    - /\d+\.\d+\.\d+\.\d+-\w+-prev/
  script:
    - V=(${CI_COMMIT_REF_NAME//[\.-]/ })
    - VDIR=${V[0]}.${V[1]}.${V[2]}.${V[3]}
    - REPO=dataflux-prev/$VDIR
    - TAG=${PROJECT}-${V[4]}
    - docker run --rm -v $(pwd):$WORKDIR_IMAGE -w $WORKDIR_IMAGE $DEP_IMAGE make build
    - make pub_pubrepo_image REPO=$REPO:$TAG DEP_IMAGE=$DEP_IMAGE
  tags:
    - cloudcare-multiarch

buildBasisImage:
  stage: build
  resource_group: production
  only:
    - /^kodo-basis[\/-_]?.*$/
  script:
    - docker buildx build --platform linux/arm64,linux/amd64 -t registry.jiagouyun.com/basis/kodo-basis:$CI_COMMIT_REF_NAME -f image/Dockerfile.basis . --push
  tags:
    - cloudcare-multiarch

buildUOSBasisImage:
  stage: build
  resource_group: production
  only:
    - /^uos-kodo-basis[\/-_]?.*$/
  script:
    - docker buildx build --platform linux/arm64,linux/amd64 -t registry.jiagouyun.com/basis/uos-kodo-basis:$CI_COMMIT_REF_NAME -f image/Dockerfile.uos.basis . --push
  tags:
    - cloudcare-multiarch

