ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ENV GOPATH=/work
ENV PATH=$PATH:$GOPATH/bin

WORKDIR /work/src/graphdb

RUN go env -w GONOPROXY="gitlab.jiagouyun.com/*" GONOSUMDB="gitlab.jiagouyun.com/*" GOPRIVATE="gitlab.jiagouyun.com/*"
RUN go env -w GOPROXY="https://goproxy.cn,direct"
RUN if [ -f /etc/apt/sources.list.d/debian.sources ]; then \
      sed -i 's/:\/\/deb.debian.org/:\/\/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list.d/debian.sources; \
    fi

COPY go.mod go.sum ./
RUN go mod download
